/**
 * PhD Pipeline Configuration
 * TASK-PHD-001 - 48-Agent PhD Pipeline
 *
 * Complete configuration for 48-agent systematic research pipeline
 * spanning 7 phases: Foundation, Discovery, Architecture, Synthesis,
 * Design, Writing, and QA.
 */

import type { IPipelineConfig, IAgentConfig, IPhaseConfig } from './pipeline-types.js';

// ==================== Phase Definitions ====================

const PHASES: IPhaseConfig[] = [
  {
    id: 1,
    name: 'Foundation',
    description: 'Initial problem analysis and framing',
    agents: [1, 2, 3, 4],
    objectives: [
      'High-level problem understanding',
      'Assumption identification',
      'Domain mapping',
      'Constraint extraction',
    ],
  },
  {
    id: 2,
    name: 'Discovery',
    description: 'Research and exploration of solution space',
    agents: [5, 6, 7, 8, 9],
    objectives: [
      'Literature review',
      'Parallel path exploration',
      'Cross-domain analogies',
      'Pattern recognition',
      'Edge case identification',
    ],
  },
  {
    id: 3,
    name: 'Architecture',
    description: 'High-level solution design',
    agents: [10, 11, 12, 13, 14, 15],
    objectives: [
      'Framework design',
      'Component specification',
      'Dependency mapping',
      'Interface definition',
      'Contradiction detection',
      'Scalability planning',
    ],
  },
  {
    id: 4,
    name: 'Synthesis',
    description: 'Integration and unification',
    agents: [16, 17, 18, 19, 20],
    objectives: [
      'Cross-validation',
      'Path unification',
      'Consistency checking',
      'Optimization',
      'Trade-off analysis',
    ],
  },
  {
    id: 5,
    name: 'Design',
    description: 'Detailed specification and algorithms',
    agents: [21, 22, 23, 24, 25],
    objectives: [
      'Algorithm design',
      'Data structure architecture',
      'Protocol specification',
      'Error handling',
      'Performance estimation',
    ],
  },
  {
    id: 6,
    name: 'Writing',
    description: 'Documentation and exposition',
    agents: [26, 27, 28, 29, 30, 31, 32],
    objectives: [
      'Technical writing',
      'Proof documentation',
      'Example generation',
      'Diagram creation',
      'Notation standardization',
      'Citation management',
      'Abstract writing',
    ],
  },
  {
    id: 7,
    name: 'QA',
    description: 'Validation, critique, and quality assurance',
    agents: [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48],
    objectives: [
      'Adversarial review',
      'Completeness checking',
      'Clarity evaluation',
      'Novelty assessment',
      'Reproducibility validation',
      'Ethics review',
      'Security analysis',
      'Performance validation',
      'Scalability verification',
      'Usability assessment',
      'Documentation review',
      'Test coverage',
      'Edge case verification',
      'Compliance checking',
      'Final synthesis',
      'Sign-off approval',
    ],
  },
];

// ==================== Agent Definitions ====================

const AGENTS: IAgentConfig[] = [
  // === PHASE 1: FOUNDATION (Agents 1-4) ===
  {
    id: 1,
    key: 'step-back-analyzer',
    name: 'Step-Back Analyzer',
    phase: 1,
    description: 'Creates high-level problem framing by stepping back from details',
    dependencies: [],
    inputs: ['problem_statement'],
    outputs: ['high_level_framing', 'key_questions', 'success_criteria'],
    timeout: 300,
    critical: true,
  },
  {
    id: 2,
    key: 'assumption-identifier',
    name: 'Assumption Identifier',
    phase: 1,
    description: 'Extracts hidden assumptions and preconditions',
    dependencies: [1],
    inputs: ['high_level_framing'],
    outputs: ['assumptions_list', 'preconditions', 'boundary_conditions'],
    timeout: 180,
  },
  {
    id: 3,
    key: 'context-mapper',
    name: 'Context Mapper',
    phase: 1,
    description: 'Maps the problem domain and related fields',
    dependencies: [1],
    inputs: ['high_level_framing'],
    outputs: ['domain_map', 'related_fields', 'terminology'],
    timeout: 240,
  },
  {
    id: 4,
    key: 'constraint-extractor',
    name: 'Constraint Extractor',
    phase: 1,
    description: 'Identifies all constraints (technical, resource, ethical)',
    dependencies: [1, 2],
    inputs: ['high_level_framing', 'assumptions_list'],
    outputs: ['constraint_list', 'must_haves', 'nice_to_haves'],
    timeout: 200,
  },

  // === PHASE 2: DISCOVERY (Agents 5-9) ===
  {
    id: 5,
    key: 'literature-reviewer',
    name: 'Literature Reviewer',
    phase: 2,
    description: 'Reviews prior work and state-of-the-art',
    dependencies: [3],
    inputs: ['domain_map', 'related_fields'],
    outputs: ['literature_summary', 'key_papers', 'research_gaps'],
    timeout: 600,
  },
  {
    id: 6,
    key: 'parallel-path-explorer',
    name: 'Parallel Path Explorer',
    phase: 2,
    description: 'Explores multiple alternative solution approaches',
    dependencies: [1, 4],
    inputs: ['high_level_framing', 'constraint_list'],
    outputs: ['alternative_paths', 'path_pros_cons'],
    timeout: 400,
  },
  {
    id: 7,
    key: 'analogy-finder',
    name: 'Analogy Finder',
    phase: 2,
    description: 'Finds analogies from other domains',
    dependencies: [3],
    inputs: ['domain_map'],
    outputs: ['analogies', 'cross_domain_insights'],
    timeout: 300,
  },
  {
    id: 8,
    key: 'pattern-recognizer',
    name: 'Pattern Recognizer',
    phase: 2,
    description: 'Identifies common patterns and structures',
    dependencies: [5, 7],
    inputs: ['literature_summary', 'analogies'],
    outputs: ['patterns', 'recurring_structures'],
    timeout: 250,
  },
  {
    id: 9,
    key: 'edge-case-hunter',
    name: 'Edge Case Hunter',
    phase: 2,
    description: 'Identifies boundary conditions and special cases',
    dependencies: [2, 4],
    inputs: ['assumptions_list', 'constraint_list'],
    outputs: ['edge_cases', 'special_conditions'],
    timeout: 220,
  },

  // === PHASE 3: ARCHITECTURE (Agents 10-15) ===
  {
    id: 10,
    key: 'framework-builder',
    name: 'Framework Builder',
    phase: 3,
    description: 'Designs high-level solution framework',
    dependencies: [6, 8],
    inputs: ['alternative_paths', 'patterns'],
    outputs: ['framework_design', 'architectural_principles'],
    timeout: 450,
  },
  {
    id: 11,
    key: 'component-designer',
    name: 'Component Designer',
    phase: 3,
    description: 'Specifies individual components/modules',
    dependencies: [10],
    inputs: ['framework_design'],
    outputs: ['component_specs', 'module_descriptions'],
    timeout: 400,
  },
  {
    id: 12,
    key: 'dependency-mapper',
    name: 'Dependency Mapper',
    phase: 3,
    description: 'Maps dependencies between components',
    dependencies: [11],
    inputs: ['component_specs'],
    outputs: ['dependency_graph', 'interaction_patterns'],
    timeout: 280,
  },
  {
    id: 13,
    key: 'interface-definer',
    name: 'Interface Definer',
    phase: 3,
    description: 'Defines APIs and interfaces between components',
    dependencies: [11, 12],
    inputs: ['component_specs', 'dependency_graph'],
    outputs: ['interface_definitions', 'api_contracts'],
    timeout: 350,
  },
  {
    id: 14,
    key: 'contradiction-analyzer',
    name: 'Contradiction Analyzer',
    phase: 3,
    description: 'Detects logical inconsistencies and contradictions',
    dependencies: [10, 11, 12, 13],
    inputs: ['framework_design', 'component_specs', 'dependency_graph', 'interface_definitions'],
    outputs: ['contradictions', 'inconsistencies', 'resolution_suggestions'],
    timeout: 500,
    critical: true,
  },
  {
    id: 15,
    key: 'scalability-planner',
    name: 'Scalability Planner',
    phase: 3,
    description: 'Plans for growth and scaling',
    dependencies: [10, 12],
    inputs: ['framework_design', 'dependency_graph'],
    outputs: ['scalability_plan', 'growth_considerations'],
    timeout: 320,
  },

  // === PHASE 4: SYNTHESIS (Agents 16-20) ===
  {
    id: 16,
    key: 'cross-validator',
    name: 'Cross Validator',
    phase: 4,
    description: 'Validates consistency across components',
    dependencies: [14],
    inputs: ['contradictions', 'resolution_suggestions'],
    outputs: ['validation_report', 'cross_checks'],
    timeout: 300,
  },
  {
    id: 17,
    key: 'unification-agent',
    name: 'Unification Agent',
    phase: 4,
    description: 'Merges parallel exploration paths',
    dependencies: [6, 10],
    inputs: ['alternative_paths', 'framework_design'],
    outputs: ['unified_approach', 'synthesis_rationale'],
    timeout: 400,
  },
  {
    id: 18,
    key: 'consistency-checker',
    name: 'Consistency Checker',
    phase: 4,
    description: 'Ensures global coherence',
    dependencies: [16, 17],
    inputs: ['validation_report', 'unified_approach'],
    outputs: ['consistency_report', 'coherence_score'],
    timeout: 280,
  },
  {
    id: 19,
    key: 'optimization-suggester',
    name: 'Optimization Suggester',
    phase: 4,
    description: 'Proposes efficiency improvements',
    dependencies: [15, 18],
    inputs: ['scalability_plan', 'consistency_report'],
    outputs: ['optimizations', 'efficiency_gains'],
    timeout: 350,
  },
  {
    id: 20,
    key: 'trade-off-analyzer',
    name: 'Trade-off Analyzer',
    phase: 4,
    description: 'Analyzes design trade-offs',
    dependencies: [17, 19],
    inputs: ['unified_approach', 'optimizations'],
    outputs: ['trade_offs', 'decision_matrix'],
    timeout: 320,
  },

  // === PHASE 5: DESIGN (Agents 21-25) ===
  {
    id: 21,
    key: 'algorithm-designer',
    name: 'Algorithm Designer',
    phase: 5,
    description: 'Designs core algorithms',
    dependencies: [17, 20],
    inputs: ['unified_approach', 'trade_offs'],
    outputs: ['algorithms', 'pseudocode'],
    timeout: 500,
  },
  {
    id: 22,
    key: 'data-structure-architect',
    name: 'Data Structure Architect',
    phase: 5,
    description: 'Designs data structures',
    dependencies: [21],
    inputs: ['algorithms'],
    outputs: ['data_structures', 'storage_schemas'],
    timeout: 400,
  },
  {
    id: 23,
    key: 'protocol-designer',
    name: 'Protocol Designer',
    phase: 5,
    description: 'Designs communication protocols',
    dependencies: [13, 21],
    inputs: ['interface_definitions', 'algorithms'],
    outputs: ['protocols', 'message_formats'],
    timeout: 380,
  },
  {
    id: 24,
    key: 'error-handler-designer',
    name: 'Error Handler Designer',
    phase: 5,
    description: 'Designs error handling and recovery',
    dependencies: [9, 21],
    inputs: ['edge_cases', 'algorithms'],
    outputs: ['error_handling', 'recovery_strategies'],
    timeout: 350,
  },
  {
    id: 25,
    key: 'performance-estimator',
    name: 'Performance Estimator',
    phase: 5,
    description: 'Estimates complexity and performance',
    dependencies: [21, 22],
    inputs: ['algorithms', 'data_structures'],
    outputs: ['complexity_analysis', 'performance_estimates'],
    timeout: 300,
  },

  // === PHASE 6: WRITING (Agents 26-32) ===
  {
    id: 26,
    key: 'technical-writer',
    name: 'Technical Writer',
    phase: 6,
    description: 'Writes clear technical exposition',
    dependencies: [21, 22, 23, 24, 25],
    inputs: ['algorithms', 'data_structures', 'protocols', 'error_handling', 'complexity_analysis'],
    outputs: ['technical_document', 'methodology_section'],
    timeout: 600,
  },
  {
    id: 27,
    key: 'proof-writer',
    name: 'Proof Writer',
    phase: 6,
    description: 'Writes formal proofs of correctness',
    dependencies: [21, 25],
    inputs: ['algorithms', 'complexity_analysis'],
    outputs: ['proofs', 'correctness_arguments'],
    timeout: 700,
  },
  {
    id: 28,
    key: 'example-generator',
    name: 'Example Generator',
    phase: 6,
    description: 'Creates illustrative examples and use cases',
    dependencies: [26],
    inputs: ['technical_document'],
    outputs: ['examples', 'use_cases', 'worked_examples'],
    timeout: 400,
  },
  {
    id: 29,
    key: 'diagram-creator',
    name: 'Diagram Creator',
    phase: 6,
    description: 'Creates visual aids and diagrams',
    dependencies: [10, 12, 26],
    inputs: ['framework_design', 'dependency_graph', 'technical_document'],
    outputs: ['diagrams', 'flowcharts', 'architecture_visuals'],
    timeout: 450,
  },
  {
    id: 30,
    key: 'notation-standardizer',
    name: 'Notation Standardizer',
    phase: 6,
    description: 'Ensures consistent notation and symbols',
    dependencies: [26, 27],
    inputs: ['technical_document', 'proofs'],
    outputs: ['notation_guide', 'symbol_definitions'],
    timeout: 250,
  },
  {
    id: 31,
    key: 'citation-manager',
    name: 'Citation Manager',
    phase: 6,
    description: 'Manages references and citations',
    dependencies: [5, 26],
    inputs: ['literature_summary', 'technical_document'],
    outputs: ['bibliography', 'citation_map'],
    timeout: 300,
  },
  {
    id: 32,
    key: 'abstract-writer',
    name: 'Abstract Writer',
    phase: 6,
    description: 'Writes executive summary/abstract',
    dependencies: [26, 27, 28],
    inputs: ['technical_document', 'proofs', 'examples'],
    outputs: ['abstract', 'executive_summary'],
    timeout: 350,
  },

  // === PHASE 7: QA (Agents 33-48) ===
  {
    id: 33,
    key: 'adversarial-reviewer',
    name: 'Adversarial Reviewer',
    phase: 7,
    description: 'Aggressively challenges the design',
    dependencies: [26, 27],
    inputs: ['technical_document', 'proofs'],
    outputs: ['attack_vectors', 'weaknesses', 'counterarguments'],
    timeout: 600,
    critical: true,
  },
  {
    id: 34,
    key: 'completeness-checker',
    name: 'Completeness Checker',
    phase: 7,
    description: 'Checks coverage and completeness',
    dependencies: [26],
    inputs: ['technical_document'],
    outputs: ['completeness_report', 'missing_elements'],
    timeout: 400,
  },
  {
    id: 35,
    key: 'clarity-evaluator',
    name: 'Clarity Evaluator',
    phase: 7,
    description: 'Evaluates readability and clarity',
    dependencies: [26, 28],
    inputs: ['technical_document', 'examples'],
    outputs: ['clarity_score', 'readability_suggestions'],
    timeout: 350,
  },
  {
    id: 36,
    key: 'novelty-assessor',
    name: 'Novelty Assessor',
    phase: 7,
    description: 'Assesses originality and contribution',
    dependencies: [5, 26],
    inputs: ['literature_summary', 'technical_document'],
    outputs: ['novelty_score', 'contributions'],
    timeout: 450,
  },
  {
    id: 37,
    key: 'reproducibility-validator',
    name: 'Reproducibility Validator',
    phase: 7,
    description: 'Validates that work can be replicated',
    dependencies: [26, 28],
    inputs: ['technical_document', 'examples'],
    outputs: ['reproducibility_checklist', 'replication_steps'],
    timeout: 400,
  },
  {
    id: 38,
    key: 'ethics-reviewer',
    name: 'Ethics Reviewer',
    phase: 7,
    description: 'Reviews ethical implications',
    dependencies: [26, 33],
    inputs: ['technical_document', 'attack_vectors'],
    outputs: ['ethics_report', 'impact_assessment'],
    timeout: 500,
  },
  {
    id: 39,
    key: 'security-analyzer',
    name: 'Security Analyzer',
    phase: 7,
    description: 'Analyzes security implications',
    dependencies: [24, 33],
    inputs: ['error_handling', 'attack_vectors'],
    outputs: ['security_report', 'vulnerability_assessment'],
    timeout: 450,
  },
  {
    id: 40,
    key: 'performance-validator',
    name: 'Performance Validator',
    phase: 7,
    description: 'Validates performance claims',
    dependencies: [25, 26],
    inputs: ['performance_estimates', 'technical_document'],
    outputs: ['performance_validation', 'benchmark_plan'],
    timeout: 400,
  },
  {
    id: 41,
    key: 'scalability-verifier',
    name: 'Scalability Verifier',
    phase: 7,
    description: 'Verifies scalability claims',
    dependencies: [15, 40],
    inputs: ['scalability_plan', 'performance_validation'],
    outputs: ['scalability_verification', 'growth_limits'],
    timeout: 380,
  },
  {
    id: 42,
    key: 'usability-assessor',
    name: 'Usability Assessor',
    phase: 7,
    description: 'Assesses usability and adoption barriers',
    dependencies: [28, 29],
    inputs: ['examples', 'diagrams'],
    outputs: ['usability_report', 'adoption_barriers'],
    timeout: 350,
  },
  {
    id: 43,
    key: 'documentation-reviewer',
    name: 'Documentation Reviewer',
    phase: 7,
    description: 'Reviews documentation quality',
    dependencies: [26, 29, 30, 31],
    inputs: ['technical_document', 'diagrams', 'notation_guide', 'bibliography'],
    outputs: ['documentation_quality', 'improvement_suggestions'],
    timeout: 400,
  },
  {
    id: 44,
    key: 'test-coverage-analyst',
    name: 'Test Coverage Analyst',
    phase: 7,
    description: 'Analyzes test coverage and gaps',
    dependencies: [9, 28],
    inputs: ['edge_cases', 'examples'],
    outputs: ['test_coverage_report', 'test_gaps'],
    timeout: 380,
  },
  {
    id: 45,
    key: 'edge-case-verifier',
    name: 'Edge Case Verifier',
    phase: 7,
    description: 'Verifies edge case handling',
    dependencies: [9, 24, 44],
    inputs: ['edge_cases', 'error_handling', 'test_coverage_report'],
    outputs: ['edge_case_verification', 'unhandled_cases'],
    timeout: 350,
  },
  {
    id: 46,
    key: 'compliance-checker',
    name: 'Compliance Checker',
    phase: 7,
    description: 'Checks compliance with standards',
    dependencies: [26, 38],
    inputs: ['technical_document', 'ethics_report'],
    outputs: ['compliance_report', 'standards_alignment'],
    timeout: 400,
  },
  {
    id: 47,
    key: 'final-synthesizer',
    name: 'Final Synthesizer',
    phase: 7,
    description: 'Synthesizes all QA feedback',
    dependencies: [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    inputs: [
      'attack_vectors', 'completeness_report', 'clarity_score', 'novelty_score',
      'reproducibility_checklist', 'ethics_report', 'security_report',
      'performance_validation', 'scalability_verification', 'usability_report',
      'documentation_quality', 'test_coverage_report', 'edge_case_verification',
      'compliance_report'
    ],
    outputs: ['qa_synthesis', 'final_recommendations', 'go_no_go_decision'],
    timeout: 600,
  },
  {
    id: 48,
    key: 'sign-off-approver',
    name: 'Sign-off Approver',
    phase: 7,
    description: 'Final approval and sign-off',
    dependencies: [32, 47],
    inputs: ['abstract', 'qa_synthesis'],
    outputs: ['approval_status', 'sign_off_certificate', 'release_notes'],
    timeout: 300,
  },
];

// ==================== Complete Configuration ====================

/**
 * Complete PhD Pipeline Configuration
 */
export const PHD_PIPELINE_CONFIG: IPipelineConfig = {
  pipeline: {
    name: 'PhD Research Pipeline',
    version: '1.0.0',
    description: '48-agent systematic research pipeline spanning 7 phases',
    totalAgents: 48,
    phases: 7,
  },
  phases: PHASES,
  agents: AGENTS,
};

/**
 * Get the default PhD pipeline configuration
 */
export function getPhDPipelineConfig(): IPipelineConfig {
  return PHD_PIPELINE_CONFIG;
}

/**
 * Get agent by ID
 */
export function getAgentById(id: number): IAgentConfig | undefined {
  return AGENTS.find(a => a.id === id);
}

/**
 * Get agent by key
 */
export function getAgentByKey(key: string): IAgentConfig | undefined {
  return AGENTS.find(a => a.key === key);
}

/**
 * Get all agents in a phase
 */
export function getAgentsByPhase(phaseId: number): IAgentConfig[] {
  return AGENTS.filter(a => a.phase === phaseId);
}

/**
 * Get all critical agents
 */
export function getCriticalAgents(): IAgentConfig[] {
  return AGENTS.filter(a => a.critical === true);
}
