/**
 * IDESC-001: Intelligent DESC v2 - Continuous Quality Monitoring
 * TASK-IDESC-LEARN-005: Implement Continuous Quality Monitoring
 * Sprint 6: Active Learning
 *
 * Background quality monitoring job that runs periodically to check
 * injection quality metrics and emit alerts when thresholds are exceeded.
 *
 * Implements:
 * - REQ-IDESC-013: Continuous quality monitoring
 * - AC-IDESC-005e: Periodic checks (configurable interval, default 1 hour)
 * - AC-IDESC-005f: Alert emission on quality degradation
 *
 * Constitution:
 * - GUARD-IDESC-006: Graceful error handling in background job
 * - GUARD-IDESC-007: Safe shutdown without data loss
 */

import type { MetricsAggregator } from './metrics-aggregator.js';
import type { IAlert } from '../types.js';

/**
 * Configuration for quality monitor
 */
export interface IQualityMonitorConfig {
  /** Check interval in milliseconds (default: 3600000 = 1 hour) */
  intervalMs: number;
  /** Whether monitoring is enabled (default: true) */
  enabled: boolean;
  /** Callback invoked when an alert is generated */
  onAlert?: (alert: IAlert) => void;
}

/**
 * Quality monitor interface
 */
export interface IQualityMonitor {
  /**
   * Start the quality monitoring job
   * Runs initial check immediately, then at configured interval
   */
  start(): void;

  /**
   * Stop the quality monitoring job
   * Clears the interval timer and stops monitoring
   */
  stop(): void;

  /**
   * Check if monitoring is currently running
   * @returns True if monitor is running
   */
  isRunning(): boolean;

  /**
   * Trigger an immediate quality check
   * Does not affect the scheduled interval checks
   * @returns Array of alerts generated by the check
   */
  checkNow(): Promise<IAlert[]>;

  /**
   * Get timestamp of last quality check
   * @returns Date of last check, or null if no checks performed yet
   */
  getLastCheckTime(): Date | null;

  /**
   * Get total number of checks performed
   * @returns Check count
   */
  getCheckCount(): number;
}

/**
 * Default configuration
 */
const DEFAULT_CONFIG: IQualityMonitorConfig = {
  intervalMs: 3600000, // 1 hour
  enabled: true
};

/**
 * QualityMonitor - Background job for continuous quality monitoring
 *
 * Periodically checks injection metrics via MetricsAggregator and emits
 * alerts when quality degradation is detected.
 *
 * Features:
 * - Configurable check interval (default: 1 hour)
 * - Immediate initial check on start
 * - Graceful error handling (GUARD-IDESC-006)
 * - Safe shutdown (GUARD-IDESC-007)
 * - Manual trigger via checkNow()
 */
export class QualityMonitor implements IQualityMonitor {
  private interval?: NodeJS.Timeout;
  private running: boolean = false;
  private lastCheckTime: Date | null = null;
  private checkCount: number = 0;
  private readonly config: IQualityMonitorConfig;

  constructor(
    private readonly metricsAggregator: MetricsAggregator,
    config?: Partial<IQualityMonitorConfig>
  ) {
    this.config = { ...DEFAULT_CONFIG, ...config };
  }

  /**
   * Start the quality monitoring job
   * Implements: AC-IDESC-005e
   */
  start(): void {
    if (this.running || !this.config.enabled) {
      return;
    }

    this.running = true;

    // Set up periodic checks
    this.interval = setInterval(async () => {
      await this.runCheck();
    }, this.config.intervalMs);

    // Run initial check immediately
    this.runCheck().catch(error => {
      console.error('[QualityMonitor] Initial check failed:', error);
    });
  }

  /**
   * Stop the quality monitoring job
   * Implements: GUARD-IDESC-007 (safe shutdown)
   */
  stop(): void {
    if (this.interval) {
      clearInterval(this.interval);
      this.interval = undefined;
    }
    this.running = false;
  }

  /**
   * Check if monitoring is running
   */
  isRunning(): boolean {
    return this.running;
  }

  /**
   * Trigger an immediate quality check
   * Implements: AC-IDESC-005f
   */
  async checkNow(): Promise<IAlert[]> {
    return this.runCheck();
  }

  /**
   * Get timestamp of last check
   */
  getLastCheckTime(): Date | null {
    return this.lastCheckTime;
  }

  /**
   * Get total number of checks performed
   */
  getCheckCount(): number {
    return this.checkCount;
  }

  /**
   * Internal method to run a quality check
   * Implements: GUARD-IDESC-006 (graceful error handling)
   */
  private async runCheck(): Promise<IAlert[]> {
    try {
      // Check all categories for quality degradation
      const alerts = await this.metricsAggregator.checkAndAlert();

      // Update check metadata
      this.lastCheckTime = new Date();
      this.checkCount++;

      // Invoke callback for each alert
      if (this.config.onAlert && alerts.length > 0) {
        for (const alert of alerts) {
          try {
            this.config.onAlert(alert);
          } catch (error) {
            // GUARD-IDESC-006: Don't fail entire check if callback fails
            console.error('[QualityMonitor] Alert callback failed:', error);
          }
        }
      }

      return alerts;
    } catch (error) {
      // GUARD-IDESC-006: Graceful error handling
      console.error('[QualityMonitor] Check failed:', error);
      return [];
    }
  }
}

/**
 * Factory function to create QualityMonitor
 *
 * @param metricsAggregator - MetricsAggregator instance for quality checks
 * @param config - Optional configuration overrides
 * @returns QualityMonitor instance
 *
 * @example
 * ```typescript
 * const monitor = createQualityMonitor(metricsAggregator, {
 *   intervalMs: 1800000, // 30 minutes
 *   onAlert: (alert) => console.log('Alert:', alert.message)
 * });
 * monitor.start();
 * ```
 */
export function createQualityMonitor(
  metricsAggregator: MetricsAggregator,
  config?: Partial<IQualityMonitorConfig>
): QualityMonitor {
  return new QualityMonitor(metricsAggregator, config);
}
